peopleEatChoice
people-eat/web-app pull request #105
Opened 2023-04-10 13:21 UTC by Llavrov

2023-04-10 14:30 UTC, CemYil03 requested changes

2023-04-10 14:30 UTC, CemYil03 commented on src/components/standard/icon/PeopleEatIconProps.ts
> +    onClick?: () => void;
Please remove this, the icon component should not have an onClick callback, only it's parent

2023-04-10 14:30 UTC, CemYil03 commented on src/components/standard/editButton/PeopleEatEditButton.stories.tsx
> +        onClick: () => console.log('click'),
Please remove all console log's

2023-04-10 14:30 UTC, CemYil03 commented on public/Mastercard.png
Can you please name it lower case Mastercard -> master-card

2023-04-10 14:30 UTC, CemYil03 commented on src/components/standard/changePhotoButton/changePhotoButton.tsx
> +import PeopleEatIcon from '~/components/standard/icon/PeopleEatIcon';
Please remove all tilde imports and replace them with a relative path

2023-04-10 14:38 UTC, Llavrov commented on src/components/standard/icon/PeopleEatIconProps.ts
> +    onClick?: () => void;
okay

2023-04-10 14:39 UTC, Llavrov commented on src/styles/globals.css
> +}
to set font-family for all components

2023-04-10 14:42 UTC, Llavrov commented on tailwind.config.cjs
> +    },
Don't know exactly, but want to try, saw this solution in documentation

2023-04-10 14:43 UTC, Llavrov commented on src/components/standard/choice/PeopleEatChoice.stories.tsx
> +        title: 'Europäisch',
okay

2023-04-10 19:09 UTC, CemYil03 commented on src/components/standard/choice/PeopleEatChoice.stories.tsx
> +        title: 'Europäisch',
Not only here, but everywhere

2023-04-11 07:26 UTC, CemYil03 approved these changes

2023-04-11 07:26 UTC, merged