Search bar
people-eat/web-app pull request #108
Opened 2023-04-15 21:36 UTC by Llavrov

2023-04-15 21:39 UTC, CemYil03 requested changes
I guess this PR is meant to replace https://github.com/people-eat/web-app/pull/107 right?

2023-04-15 21:39 UTC, CemYil03 commented on src/components/standard/search/PeopleEatSearch.tsx
> +import PeopleEatIcon from '~/components/standard/icon/PeopleEatIcon';
Tilde imports

2023-04-15 21:39 UTC, CemYil03 commented on src/components/standard/search/PeopleEatSearch.tsx
> +const SEARCH_TABS = ['Deine Stadt', 'Anzahl der Personen', 'Kinder', 'Date'];
This will probably fail the pipeline as it is german words

2023-04-15 21:39 UTC, CemYil03 commented on src/components/standard/search/PeopleEatSearch.tsx
> +    const temporary = 'absolute left-[50vw] translate-x-[-50%]';
I think you forgot to remove this line?

2023-04-15 21:39 UTC, CemYil03 commented on src/pages/index.tsx
> +import PeopleEatSearch from '~/components/standard/search/PeopleEatSearch';
Tilde import

2023-04-15 21:40 UTC, CemYil03 commented on src/components/standard/search/PeopleEatSearch.tsx
> +const SEARCH_TABS = ['Deine Stadt', 'Anzahl der Personen', 'Kinder', 'Date'];
And right on top ⬆ tilde imports...

2023-04-15 21:41 UTC, Llavrov commented on src/components/standard/search/PeopleEatSearch.tsx
> +    const temporary = 'absolute left-[50vw] translate-x-[-50%]';
Yep, can just delete it - styles for centered searchbar

2023-04-15 21:49 UTC, Llavrov commented on src/components/standard/search/PeopleEatSearch.tsx
> +    const temporary = 'absolute left-[50vw] translate-x-[-50%]';
Also, this pr can replace #107

2023-04-16 07:48 UTC, CemYil03 approved these changes
I merge this now so I can clean up the commit history

2023-04-16 08:48 UTC, closed without merging

2023-04-16 08:49 UTC, CemYil03 commented
I added these changes manually, because of to many merge conflics. GitHub automatically closed this pr.
Don't forget to rebase before you continue developing.