PEMealCard, PEMealCardTouch, PEMealComponent, PEMealComponentTouch, PEToggle
people-eat/web-app pull request #141
Opened 2023-04-26 23:43 UTC by Llavrov

2023-04-27 06:11 UTC, CemYil03 requested changes
💬

2023-04-27 06:11 UTC, CemYil03 commented on public/chef.png
Please don't add this image back in. I think we talked about the switch to image urls instead of static image assets.

2023-04-27 06:11 UTC, CemYil03 commented on public/icons/food-delivery.svg
I can't see any differences between `public/icons/food-delivery.svg` and `public/icons/food.svg` 🤔
Do we really need both?

2023-04-27 06:11 UTC, CemYil03 commented on src/components/cards/mealComponent/PEMealComponentTouch.tsx
> +            onClick={(): void => onClick?.()}
Wouldn't this work just as well?

```suggestion
            onClick={onClick}
```

2023-04-27 06:11 UTC, CemYil03 commented on src/components/cards/mealComponent/PEMealComponent.tsx
> +export default function PEMealComponent({ onClick, mealTitle, mealDescription, mealPicture }: PEMealComponentProps): ReactElement {
I think we did not add the suffix `Component` to any other component. Consider renaming it to something like `PEMealCard`.

2023-04-27 06:11 UTC, CemYil03 commented on src/components/cards/mealComponent/PEMealComponent.tsx
> +            onClick={(): void => onClick?.()}
```suggestion
            onClick={onClick}
```

2023-04-27 06:11 UTC, CemYil03 commented on src/components/cards/mealComponent/PEMealComponentTouch.tsx
> +export default function PEMealComponentTouch({ onClick, mealTitle, mealDescription, mealPicture }: PEMealComponentProps): ReactElement {
Maybe `PEMealCardMobile`?

2023-04-29 10:35 UTC, Llavrov commented on src/components/cards/mealComponent/PEMealComponent.tsx
> +export default function PEMealComponent({ onClick, mealTitle, mealDescription, mealPicture }: PEMealComponentProps): ReactElement {
Hm, I also thought about that, but we already have PEMealCard

2023-04-29 16:33 UTC, CemYil03 requested changes
Good progress 👍

2023-04-29 16:33 UTC, CemYil03 commented on src/components/standard/icon/Icon.tsx
> +    foodDelivery = '/icons/food-delivery.svg',
This one can be deleted
```suggestion
```

2023-04-29 16:33 UTC, CemYil03 commented on src/components/standard/button/PEToggle.tsx
> +    const [toggle, setToggle] = useState(active);
You actually don't need an internal state, active and onClick which are passed in can do the same job.

2023-04-29 16:33 UTC, CemYil03 commented on src/components/cards/mealComponent/PEMealComponent.tsx
> +    mealPicture?: string;
I think inside of a Meal component a meal prefix becomes kind of redundant.

```suggestion
    title?: string;
    description?: string;
    imageUrl?: string;
```

2023-04-29 16:33 UTC, CemYil03 commented on src/components/cards/chefCard/PEChefCard.stories.tsx
> +        imageUrl: '/chef.png',
I guess this doesn't work. Please add any url pointing to an image like `https://...`

2023-04-30 17:40 UTC, CemYil03 requested changes

2023-04-30 17:40 UTC, CemYil03 commented on src/components/standard/button/PEToggle.tsx
> +            className={classNames(baseClassNames, {
```suggestion
export default function PEToggle({ onClick, active, title }: PEToggleProps): ReactElement {
    const baseClassNames =
        'w-[70px] h-[70px] flex items-center border-solid gap-2 p-3 justify-center w-full rounded-15 border-0 transition-all';

    return (
        <div
            onClick={onClick}
            className={classNames(baseClassNames, {
```

2023-04-30 18:17 UTC, CemYil03 approved these changes

2023-04-30 18:17 UTC, merged