PEFullScreenDialog and HomePageSearchMobile
people-eat/web-app pull request #198
Opened 2023-05-10 19:48 UTC by Llavrov

2023-05-10 19:58 UTC, CemYil03 requested changes
Please move the icon changes (adding files and extending the enum) to its own commit

2023-05-10 19:58 UTC, CemYil03 commented on src/components/pages/home/index.tsx
I don't see any useful change here, please revert erverything in this file.

2023-05-10 19:58 UTC, CemYil03 commented on src/components/pages/home/search/HomePageSearchMobile.tsx
> +import PEIconButton from '~/components/standard/iconButton/PEIconButton';
Remove tilde imports

2023-05-10 19:58 UTC, CemYil03 commented on src/components/pages/home/search/HomePageSearchMobile.tsx
> +            className={'hidden lg:flex w-full justify-between px-6 py-2 box-border items-center shadow-primary'}
Was beeter before, please revert

2023-05-10 19:58 UTC, CemYil03 commented on src/components/standard/dialogs/PEDialog.tsx
> +import PEIconButton from '~/components/standard/iconButton/PEIconButton';
Remove tilde imports

2023-05-10 19:58 UTC, CemYil03 commented on src/components/standard/dialogs/PEDialog.tsx
> +const Transition = React.forwardRef(function Transition(
Import forwardRef directly from the react package *if possible

2023-05-10 19:58 UTC, CemYil03 commented on src/components/standard/dialogs/PEDialog.tsx
> +    }, [isOpen]);
Is this really necessary? Consider refactoring

2023-05-10 19:58 UTC, CemYil03 commented on package.json
> +        "react-draggable": "^4.4.5",
I don't see this being used anywhere 🤔

2023-05-10 20:09 UTC, CemYil03 commented on src/components/pages/home/index.tsx
*only a few useful changes. Please keep the transition from `{''}` to `""` and also the `VStack`s and `HStack`s. They are supposed to increase readbility of the code

2023-05-10 21:02 UTC, Llavrov commented on src/components/standard/dialogs/PEDialog.tsx
> +    }, [isOpen]);
yes, to update open state, cause without we can't mount from outside, think because MUI compontent

2023-05-10 21:03 UTC, Llavrov commented on package.json
> +        "react-draggable": "^4.4.5",
yes, forgot to delete, just tried to use it before for dialog, but now just use without this lib

2023-05-11 05:58 UTC, CemYil03 approved these changes

2023-05-11 06:13 UTC, merged