sign-in sign-up pages mobile versions
people-eat/web-app pull request #201
Opened 2023-05-11 12:01 UTC by Llavrov

2023-05-11 12:17 UTC, CemYil03 commented on src/components/pages/signIn/index.tsx
> +                        </div>
Please don't use css hidden, instead make it TypeScript driven

2023-05-11 12:29 UTC, Llavrov commented on src/components/pages/signIn/index.tsx
> +                        </div>
oh, okay, got you

2023-05-11 12:32 UTC, Llavrov commented on src/components/pages/signIn/index.tsx
> +                        </div>
But could you please write an example, how to make it hidden by ts instead css

2023-05-11 22:13 UTC, CemYil03 requested changes

2023-05-11 22:13 UTC, CemYil03 commented on src/components/header/PEHeader.tsx
> +            ) : null}
So for mobile we would not show anything now?

2023-05-11 22:13 UTC, CemYil03 commented on src/components/header/PEHeaderMobile.tsx
> +    }, []);
It is not even sure if we really want it to be sticky, should check with Natalia and Daniel.

2023-05-11 22:13 UTC, CemYil03 commented on src/components/pages/chefProfile/index.tsx
> +            <PEHeaderMobile />
Here is the correct place where we check if we are on mobile or desktop, not within the components themselves:

```suggestion
            {isDesktop && <PEHeader />}
            {isMobile && <PEHeaderMobile />}
```

2023-05-11 22:13 UTC, CemYil03 commented on src/components/pages/chefProfile/index.tsx
> +            <PEHeaderMobile />
Same thing for every other page

2023-05-11 22:13 UTC, CemYil03 commented on src/components/pages/signIn/index.tsx
> +                        {responsive.isDesktop ? <div style={{ flex: 1 }}></div> : null}
In most cases if you use the ternary operator defaulting to `null`, consider just using the `&&` operator.
Also replace line 82 with a `<Spacer />`. This is exactly what it does, having `flex: 1`

2023-05-11 22:13 UTC, CemYil03 commented on src/components/pages/signUp/index.tsx
> +            {responsive.isDesktop ? (
Switch to `&&` here as well

2023-05-12 06:43 UTC, Llavrov commented on src/components/header/PEHeader.tsx
> +            ) : null}
oh, yes, is good idea just to show MobileHeader

2023-05-12 07:44 UTC, merged