Chef registration
people-eat/web-app pull request #249
Opened 2023-05-19 12:48 UTC by Llavrov

2023-05-19 16:36 UTC, CemYil03 requested changes

2023-05-19 16:36 UTC, CemYil03 commented on src/components/pages/cookSignUp/index.tsx
> +];
For this we have an enumeration / union of string literals called `CookRank` in the generated file.

2023-05-19 16:36 UTC, CemYil03 commented on src/components/pages/cookSignUp/index.tsx
> +];
languageId

2023-05-19 16:36 UTC, CemYil03 commented on src/components/pages/cookSignUp/index.tsx
> +                        }}
This change doesn't bring any benefit except for more lines of code...

2023-05-19 16:36 UTC, CemYil03 commented on src/components/pages/cookSignUp/index.tsx
> +                        title="Language"
Actually it is about a list of languages the user speaks, so no singleSelector and the label was before correct too...

2023-05-19 16:36 UTC, CemYil03 commented on src/components/standard/buttons/PEButton.tsx
> +            }}
Why the changes to PEButton at all?

2023-05-19 16:36 UTC, CemYil03 commented on src/components/standard/dropdown/PEDropdown.tsx
> +    singleSelector?: boolean;
I think we will have to put more thought in a single select drop down. Like this it would still trigger the callbacks and internally check multiple options. We would have clear the selectedOptionIndices evertime a new option is clicked, to make sure really only one can be selected.

2023-05-20 13:32 UTC, Llavrov commented on src/components/standard/buttons/PEButton.tsx
> +            }}
We just talked about accessibility to use button with 'TAB' btn

2023-05-20 13:40 UTC, Llavrov commented on src/components/standard/dropdown/PEDropdown.tsx
> +    singleSelector?: boolean;
Yes, I also thought about this option, can do it in another pr

2023-05-20 15:59 UTC, CemYil03 commented on src/components/standard/buttons/PEButton.tsx
> +            }}
I already did that a few days ago. Changed `div` to `button`. That fixed it. Do Natalia and Daniel know about the visual changes this would introduce?

2023-05-20 16:24 UTC, CemYil03 commented on src/components/cards/reviewCard/PEReviewCardChef.tsx
> -import { type CookRank } from '../../../data-source/generated/graphql';
Please don't remove

2023-05-20 16:53 UTC, Natanta94 approved these changes

2023-05-20 17:04 UTC, merged