bugs with chef-profile edit menu/meal screens
people-eat/web-app pull request #331
Opened 2023-06-20 17:43 UTC by Llavrov

2023-06-20 19:21 UTC, CemYil03 requested changes

2023-06-20 19:21 UTC, CemYil03 commented on src/components/pages/chefProfile/mealsTab/ChefProfilePageMealsTab.tsx
> +                        void refetch();
Why would you refetch on cancel? Wouldn't you only refetch if something has changed?
I would suggest an `onClose` and an `onCloseWithChanges` callback. One which onCloseWithChanges would refetch and onClose not.

2023-06-20 19:21 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/ChefProfilePageMenusTab.tsx
> +                                className="relative PEMenuCard editMenu"
What is css classname editMenu supposed to do?

2023-06-20 20:51 UTC, Llavrov commented on src/components/pages/chefProfile/menusTab/ChefProfilePageMenusTab.tsx
> +                                className="relative PEMenuCard editMenu"
It's for selecting parent component with edit/delete dropdown on click.

if (!isParentNodeElementHasClass(event, 'editMenu')) setEditMenuOpen(false);

2023-06-21 05:22 UTC, CemYil03 requested changes

2023-06-21 05:22 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/createMenuStep2/CreateCookMenuCourse.tsx
> +                                    title={`${mealType}FFF`}
What is this about?

2023-06-21 05:22 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/editMenuStep2/ChefProfilePageEditMenusStep2.tsx
> +        onSaveUpdates();
Actually we only want to call this if the action was successful. updateGreetingFromKitchen().then(result => result.data.cook.success ...)

2023-06-21 05:22 UTC, CemYil03 commented on src/components/pages/chefProfile/personalTab/section5/ChefProfileSection5.tsx
> +    const filteredLanguages = languages.filter((language) => language.title.toLowerCase().includes(languageSearchText.toLowerCase()));
Perfect, thank you!

2023-06-21 06:32 UTC, CemYil03 requested changes

2023-06-21 06:32 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/createMenuStep2/CreateCookMenuCourse.tsx
> +                                    title={`${mealType}FFF`}
Still no answer??

2023-06-21 06:33 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/editMenuStep2/ChefProfilePageEditMenusStep2.tsx
> +        onSaveUpdates();
Not changed either...

2023-06-21 08:05 UTC, CemYil03 approved these changes

2023-06-21 08:06 UTC, merged