PEOPLEEAT-016: mobile menu for chef-profile tab
people-eat/web-app pull request #335
Opened 2023-06-21 09:52 UTC by Llavrov

2023-06-21 21:33 UTC, CemYil03 requested changes
I like the organisation to group the edit pages and the create pages together 👍
For the rest I think a little demo in tomorrows Daily would be helpful.

2023-06-21 21:33 UTC, CemYil03 commented on src/components/standard/mobileMenu/PEMobileMenu.tsx
> +                            key={`${menuTab.title}_${menuTab.link}`}
Why do you always concatenate some strings, are there any benefits in contrast to just using the index provided by the map function?

2023-06-21 21:33 UTC, CemYil03 commented on src/components/standard/mobileMenu/PEMobileMenu.tsx
> +                    <Button style={{ color: 'rgba(31, 31, 31, 0.8)', textTransform: 'capitalize' }}>{t('about-us')}</Button>
Please remove all textTransforms. Instead correct them in the translation files. I think this would be the cleaner way.

2023-06-21 21:33 UTC, CemYil03 commented on src/components/pages/chefProfile/index.tsx
> +];
I think I just need some explanation on why this format is needed compared to before.

2023-06-22 10:30 UTC, Llavrov commented on src/components/standard/mobileMenu/PEMobileMenu.tsx
> +                            key={`${menuTab.title}_${menuTab.link}`}
Just always think about situations, when one of components will be unmount and there will be components with the same keys that gives warn / error

2023-06-22 10:31 UTC, Llavrov commented on src/components/standard/mobileMenu/PEMobileMenu.tsx
> +                    <Button style={{ color: 'rgba(31, 31, 31, 0.8)', textTransform: 'capitalize' }}>{t('about-us')}</Button>
So, It's already correct, but MUI button make it uppersize

2023-06-22 10:32 UTC, Llavrov commented on src/components/pages/chefProfile/index.tsx
> +];
It's for mobile header, were we use right side menu with tabs with link

2023-06-23 05:40 UTC, CemYil03 requested changes

2023-06-23 05:40 UTC, CemYil03 commented on src/components/cards/menuCard/PEMenuCardMobile.tsx
> +                    {!imageUrls.length ? <PEIcon icon={Icon.food} edgeLength={52} /> : null}
Why these changes? Personally I prefer the shorter syntax

2023-06-23 05:40 UTC, CemYil03 commented on src/components/pages/chefProfile/personalTab/section5/ChefProfileSection5.tsx
> +                            ].map(({ languageId, title }, index) => (
This wasn't here yesterday either. Has to be removed

2023-06-23 13:53 UTC, CemYil03 commented on src/components/pages/chefProfile/menusTab/editMenu/editMenuStep1/ChefProfilePageEditMenusStep1.tsx
> +        if (menu.kitchen !== selectedKitchen) {
Only compare the kitchenId's, not the entire object

2023-06-23 14:04 UTC, CemYil03 approved these changes

2023-06-23 14:04 UTC, merged