add apollo-client configuration
people-eat/web-app pull request #35
Opened 2023-03-20 22:13 UTC by Llavrov

2023-03-21 09:16 UTC, CemYil03 commented on apps/web-app-e2e/project.json
> +            }
I don't think this belongs to this PR

2023-03-21 09:17 UTC, CemYil03 commented on apps/web-app-e2e/tsconfig.json
> +    ]
This doesn't belong here either

2023-03-21 09:19 UTC, CemYil03 commented on apps/web-app/apollo-client.ts
> +export default client;
Can you make this in one line please? Like:

```typescript
export default const client ...
```

2023-03-21 09:19 UTC, CemYil03 commented on apps/web-app/components/Button.stories.tsx
> +// Button.stories.ts|tsx
Delete this file

2023-03-21 09:19 UTC, CemYil03 commented on apps/web-app/components/Button.tsx
> +import { Button } from '@mui/material';
Delete this file

2023-03-21 09:21 UTC, CemYil03 commented on package-lock.json
How is this even possible? We forbid to use npm install...
Definitely delete

2023-03-22 16:07 UTC, Llavrov commented on apps/web-app/apollo-client.ts
> +export default client;
ts tells me, that he don't like this way(
swears that he expects - TS1109: Expression expected.

2023-03-23 06:26 UTC, CemYil03 commented on apps/web-app/apollo-client.ts
> +export default client;
Okay, no problem then 👍

2023-03-23 06:31 UTC, CemYil03 requested changes
Some more comments 💬 And can you please squash your commit into a single one (git fixup)?

2023-03-25 15:34 UTC, CemYil03 approved these changes

2023-03-25 15:36 UTC, merged