PEOPLEEAT-031: privacy-policy/terms-and-conditions links and open new…
people-eat/web-app pull request #385
Opened 2023-07-01 15:52 UTC by Llavrov

… window tab

2023-07-01 19:51 UTC, CemYil03 commented on src/components/pages/cookSignUp/index.tsx
> +                                    rel="noopener noreferrer"
Gould you explain what `rel="noopener noreferrer"` is supposed to do? I have a feeling it doesn't change the behaviour

2023-07-01 20:08 UTC, Llavrov commented on src/components/pages/cookSignUp/index.tsx
> +                                    rel="noopener noreferrer"
It's open a new tab in brawser

2023-07-05 21:50 UTC, CemYil03 requested changes
Both Booking Request Pages are missing. In the task they are all listed...

2023-07-05 21:50 UTC, CemYil03 commented on locales/fr/chef-sign-up.json
>      "terms-and-conditions-label": "J'ai lu et j'accepte les termes et conditions",
This look wrong
```suggestion
    "terms-and-conditions-label": "J'ai lu et j'accepte les",
```

2023-07-06 06:24 UTC, merged